---
abstract: 'The Illicit Love Child of Moose and POE'
author:
  - 'Chris Prather  C<< <chris@prather.org> >>'
build_requires:
  Test::More: 0.42
distribution_type: module
generated_by: 'Module::Install version 0.80'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-POE
no_index:
  directory:
    - ex
    - inc
    - t
requires:
  Moose: 0.73
  MooseX::Async: 0.01
  POE: 0.9999
  Sub::Name: 0.04
resources:
  license: http://dev.perl.org/licenses/
version: 0.201
