---
abstract: 'The Illicit Love Child of Moose and POE'
author:
  - 'Chris Prather  C<< <chris@prather.org> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.90
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-POE
no_index:
  directory:
    - ex
    - inc
    - t
requires:
  Moose: 0.90
  POE: 1.004
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/perigrin/moosex-poe.git
version: 0.209
